[theme]
primaryColor = "#4cc9f0"
backgroundColor = "#0d1b2a"
secondaryBackgroundColor = "#1b263b"
textColor = "#ffffff"
font = "sans-serif"
base = "dark"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 100
